In [1]:
import torch
import numpy as np
from matplotlib import pyplot as plt

mode = 'validation'
data_path = '../vis/val/426.0.dat'

data_point = torch.load(data_path).numpy()
print(data_point.shape)

if mode == 'validation':
    vid_len = 480
    mask = data_point[:, :vid_len]
    final = data_point[:, vid_len:vid_len*2]
    bound = data_point[:, vid_len*2:]

    for ind in range(1, data_point.shape[0], 1):
        f, axarr = plt.subplots(2, sharex=True, figsize=(16,6))
        axarr[0].plot(mask[ind, :], label="differentiable mask (eq. 14)", linewidth=3)
        axarr[1].plot(final[ind, :], color='#ff8c00', label="gated mask (eq. 17)", linewidth=3)
        axarr[0].set_title('Visualization of differentiable mask and gated mask', fontsize=16)
        axarr[0].set_ylabel('mask magnitude', fontsize=14)
        axarr[1].set_xlabel('frame index (window size = 480)', fontsize=16)
        axarr[1].set_ylabel('mask magnitude', fontsize=14)
        axarr[0].legend(loc='upper right', fontsize='x-large')
        axarr[1].legend(loc='upper right', fontsize='x-large')
        # plt.figure(figsize=(16, 3))
        # plt.plot(mask[ind, :], label="learned mask")
        # plt.plot(final[ind, :], label="final mask")
        
        # plt.plot(bound[ind, [0,0,1,1]], [0,1,1,0], marker='o', label="anchor window")
        # plt.plot(bound[ind, [2,2,3,3]], [0,1,1,0], marker='x', label="offset-based window")
        plt.xlim([0, 480])
        # plt.xlabel("frame index (window size is 480)", fontsize="x-large")
        # plt.ylabel("mask magnitude", fontsize="x-large")
        # plt.legend(fontsize="x-large")
        plt.show()     
else:
    vid_len = 480
    mask = data_point[:, :vid_len]
    gt = data_point[:, vid_len:vid_len*2]
    bound = data_point[:, vid_len*2:]

    for ind in range(1, data_point.shape[0], 1):
        plt.figure(figsize=(16, 3))
        plt.plot(mask[ind, :])
        plt.plot(1.1*gt[ind, :])
        plt.plot(bound[ind, [0,0,1,1]], [0,1,1,0], marker='o')
        plt.plot(bound[ind, [2,2,3,3]], [0,1,1,0], marker='x')
        plt.xlim([0, 480])
        plt.xlabel("frame index (window size is 480)")
        plt.ylabel("mask magnitude")
        plt.show()        

UnpicklingError: invalid load key, '{'.

In [85]:
print(bound)

[[  2.00000000e+01   2.31000000e+02   1.01141205e+01   2.45435623e+02]
 [  1.32000000e+02   2.93000000e+02   1.22959846e+02   2.93957306e+02]
 [  1.92000000e+02   3.53000000e+02   2.05340057e+02   3.41939728e+02]
 [  1.40000000e+02   3.51000000e+02   1.47582611e+02   3.83385956e+02]
 [  2.48000000e+02   4.09000000e+02   2.58633484e+02   4.24982910e+02]
 [  1.20000000e+01   1.73000000e+02   1.81219406e+01   1.37454498e+02]
 [  4.40000000e+01   2.05000000e+02   5.07387695e+01   1.98644730e+02]
 [  4.80000000e+01   2.99000000e+02   3.57919769e+01   3.25562378e+02]
 [  1.56000000e+02   3.17000000e+02   1.64964142e+02   3.06920532e+02]
 [  7.20000000e+01   2.33000000e+02   9.34164429e+01   2.28004303e+02]
 [  2.16000000e+02   3.77000000e+02   2.22094940e+02   3.77673065e+02]
 [  0.00000000e+00   1.11000000e+02   5.39256287e+00   1.06142738e+02]
 [  1.02000000e+02   3.53000000e+02   7.34800873e+01   4.17012512e+02]
 [  3.12000000e+02   4.23000000e+02   3.10662781e+02   4.13500732e+02]
 [  1.